config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to:'regions#index'
  get '/regions', to: 'regions#index'
  get '/regions/:id', to: 'regions#show'

  get '/pokemons', to: 'pokemons#index'
  get '/pokemons/:id', to: 'pokemons#show'
  get '/regions/:id/pokemons', to: 'regions_pokemons#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
belongs_to :region 
validates_presence_of :name 
validates_presence_of :pokemon_weight
validates :has_evolution, inclusion:[true, false]
end

app/models/region.rb
class Region < ApplicationRecord

  has_many :pokemons 
  validates_presence_of :name
  validates_presence_of :total_num_in_region
  validates :caught_all_in_region, inclusion:[true, false]

  def self.order_by_creation #STORY 6
    self.order(created_at: :desc)
  end

  def pokemons_count #STORY 7
    self.pokemons.count
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def index
    @pokemons = Pokemon.all

  end

  def show 
    @pokemons = Pokemon.find(params[:id])
  end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  def index  
    @regions = Region.all.order_by_creation
  end

  def show
    @region = Region.find(params[:id])
  end
end 

app/controllers/regions_pokemons_controller.rb
class RegionsPokemonsController < ApplicationController
  def index  
    @regions = Region.find(params[:id]) 
    @pokemons = @regions.pokemons
  end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokedex</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemons/index.html.erb
<%= link_to "Pokemon page", pokemons_path(@pokemon) %>
<%= link_to "Regions page", regions_path(@region)%>
<body>
<body style="background-color:skyblue">
<h1> Pokemon Index Page </h1>

<% @pokemons.each do |pokemon| %>
<h3><a href="/pokemons/<%=pokemon.id %>"> 
<%= pokemon.name %> </h3></a>
<p>Weight: <%= pokemon.pokemon_weight %></p>
<p>Has Evolution: <%= pokemon.has_evolution%></p>
<% end %>
</body>

app/views/pokemons/show.html.erb
<%= link_to "Pokemon page", pokemons_path(@pokemons) %>
<%= link_to "Regions page", regions_path(@regions)%>
<body>
<body style="background-color:skyblue">
<h1>Pokemon Show page</h1>

<h3><%= @pokemons.name %></h3>
<img src="https://thumbs.gfycat.com/AbandonedFrailEasternnewt-max-1mb.gif" alt="psyduck gif" width="200" height="140">
<p>Weight: <%= @pokemons.pokemon_weight %></p>
<p>Has Evolution: <%= @pokemons.has_evolution %></p>
</body>

app/views/regions/index.html.erb
<%= link_to "Pokemon page", pokemons_path(@pokemon) %>
<%= link_to "Regions page", regions_path(@region)%>
<body>
<body style="background-color:skyblue">
<h1> Region Index Page </h1>

<% @regions. each do |region| %>
<h3><%= region.name %> </h3>
<p><%= region.created_at%></p>
<p>Total number in region:<%= region.total_num_in_region%></p>
<p>Caught all regional pokemon?: <%= region.caught_all_in_region%></p>
<% end %>
</body>

app/views/regions/show.html.erb
<%= link_to "Pokemon page", pokemons_path(@pokemon) %>
<%= link_to "Regions page", regions_path(@region)%>
<body>
<body style="background-color:skyblue">
<h1>Region Show page</h1>

<p>Region name: <%= @region.name %></p>
<img src="https://static.wikia.nocookie.net/pokemon/images/f/fe/Johto_HGSS.png" alt="Johto" width="400" height="240">

<p>Caught all in region?: <%= @region.caught_all_in_region %></p>
<p>Total number in region: <%= @region.total_num_in_region %></p>
<p>Region Pokemon count: <%= @region.pokemons_count %> </p>
<%= link_to "Registered Johto Pokemons", "/regions/#{@region.id}/pokemons", method: :get %>
</body>

app/views/regions_pokemons/index.html.erb
<%= link_to "Pokemon page", pokemons_path(@pokemon) %>
<%= link_to "Regions page", regions_path(@region)%>
<body>
<body style="background-color:skyblue">
<h1> Pokemon Index Page </h1>

<% @pokemons.each do |pokemon| %>
<h3><a href="/pokemons/<%=pokemon.id %>"> 
<%= pokemon.name %> </h3></a>
<%= pokemon.pokemon_weight %>
<%= pokemon.has_evolution %>
<% end %>
</body>